language: java

env:
  global:
    - ANDROID_HOME=~/android-sdk-linux
    - secure: "eMONRmh/28CnRRhnK1hkoJwrAFptyLwQ4Z5hGP/ccywZmKOUlkkDwapbcKkk\narSLHGY8Ybn+QMj/L8DVm+KnTApNq9cWc+1DNbMhZuANzraDHaBrdIdJeBtO\nQEG2bkaYwtYEmUYPBqSLMen/Vs8c0eVWQISU76UIvvPknA/PHA0="

before_install:
  - export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
  - wget http://dl.google.com/android/android-sdk_r20.0.3-linux.tgz
  - tar xfz android-sdk_r20.0.3-linux.tgz -C ~
  - android update sdk --filter platform-tools,android-8,extra-android-support --no-ui --force
  - echo no | android create avd -n android2.2 -t android-8 --skin QVGA
  - mv $ANDROID_HOME/tools/emulator $ANDROID_HOME/tools/emulator-old
  - ln -s $ANDROID_HOME/tools/emulator-arm $ANDROID_HOME/tools/emulator
  - alias grepd="grep -v -e 'Downloaded:' -e 'Downloading:'"

install: echo
script: "mvn clean install -P ci | grepd"

after_script:
  - mvn pl.project13.maven:git-commit-id-plugin:revision ghDownloads:upload -P ci --projects RapidFTR-Android --fail-never | grepd

notifications:
  email: false
  irc: "irc.freenode.org#rapidftr"
