language: java

env:
  global:
    - ANDROID_HOME=~/android-sdk-linux
    - secure: "eATae5kWD2tL3xtUdQjk4T5RWn4zv5OS4QXjwL9q/E4ntzge3rVPRGVSyS5/\nL/d48QLlliDzC6d7ycFVyEZC0OLzpHNER56vhP4YY9yfLygHr+NQJizPEiMJ\nPj5vUu9+qfOb3icQuQYDamuOCT7CxnVXSxVApfpFSSGz1YFpwfs="

before_install:
  - export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
  - wget http://dl.google.com/android/android-sdk_r21-linux.tgz
  - tar xfz android-sdk_r21-linux.tgz -C ~
  - android update sdk --filter platform-tools,android-8,extra-android-support --no-ui --force
  - echo no | android create avd -n android2.2 -t android-8 --skin QVGA

install: echo
script: mvn clean install -P with-emulator

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#rapidftr"
    template:
      - "[%{repository}] [%{commit}] [%{author}] %{message} - %{build_url}"
